### ISSUE TITLE
average_sentence_length function

### ISSUE THREAD

**Issue by 15mikesmith** [shaji1411/pwp-capstones#2]
The function uses split which causes causes whitespace to be counted.

E.g average_sentence_length('This is a sentence. ') returns 2 since it breaks the text into a variable called sentences_length which consists of [4,0] when it should return just 4 and sentences_length should be [4].

Whitespace is filtered out later in the program so again this does not impact functionality.

**Comment by shaja-yacob** [comment]
I think it is because i used list comprehension. I am closing it since it doesn't impact functionality.
