### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by 15mikesmith** [shaji1411/pwp-capstones#3]
Criteria 1: Valid Python Code

Score Level: 4 Meets Expectations
Comment(s): Code included runs without any errors.

Criteria 2: Implementation of Project Requirements

Score Level: 4
Comment(s): Code produces the suite of functions and classes required of it and calls them in an appropriate order.

Criteria 3: Software Architecture

Score Level: 4
Comment(s): Classes and functions are well defined

Criteria 4: Uses Python Language Features

Score Level: 4
Comment(s): Python language features are used correctly

Criteria 4: Produces Accurate Output

Score Level: 4
Comment(s): Code output is accurate

Overall Score: 20/20

Great job! The project is completes all the requirements and has superb software design. All functions are concise and simple enough to understand. Variables are also all named appropriately and the student made good use of built-in python functions.

**Comment by shaja-yacob** [comment]
Hello Mike, 
Thanks for reviewing my code and your comments are very valuable.
